import { Router } from 'express';
import { validate } from '../../middleware/validate.js';
import { requireAuth } from '../auth/index.js';
import { contactController } from './contact.module.js';
import { contactRateLimiter } from './contact.rate-limiter.js';
import { contactIdParams, contactInput, contactListQuery } from './contact.schemas.js';
export const contactRouter = Router();
contactRouter.post('/', validate(contactInput), contactRateLimiter, contactController.submit);
export const adminContactRouter = Router();
adminContactRouter.use(requireAuth);
adminContactRouter.get('/contacts', validate(contactListQuery), contactController.list);
adminContactRouter.get('/contacts/:id', validate(contactIdParams), contactController.get);
